### ISSUE TITLE
Launcher won't open

### ISSUE THREAD

**Issue by archerthefost** [open-goal/launcher#117]
Launcher does not open at all, both from the desktop shortcut and from the exe file in the directory itself. I tried installing it on every disk but it still won't open. How do I install it so it can run?

**Comment by xTVaser** [comment]
I assume that means it successfully installed.

Share your logs from `C:/Users/<name>/AppData/Roaming/OpenGOAL-Launcher/logs`  for hopefully something that can be used to help you.  

Otherwise this has no information that I can use -- I've installed it on fresh environments multiple times successfully.

**Comment by archerthefost** [comment]
I don't have OpenGOAL-Launcher folder in AppData/Roaming for whatever reason so I can't really find the logs, could them be in any another directory?

**Comment by archerthefost** [comment]
I don't have OpenGOAL-Launcher folder in AppData/Roaming for whatever reason so I can't really find the logs, could them be in any another directory?

**Comment by xTVaser** [comment]
No that makes sense if the launcher can't open at all (it will create the directory when it tries to create the logs if it doesn't already exist).

I just tried opening the launcher with the directory deleted, hoping that was the bug but it works as expected.

Are you using Windows 10/11?

**Comment by Phantom092** [comment]
I am also facing this issue. I also couldn't find a log file after following your instruction xTVaser.
I followed the youtube link https://www.youtube.com/watch?v=p8I9NfuZOgE on the OpenGOAL website and followed it 1:10 where all I need to do is double click the application for the launcher to launch and it did not, been searching for a solution for about 20mins and I'm lost. Any help will be appreciated

**Comment by xTVaser** [comment]
Seems to be the same issue as #130 closing this as a duplicate

**Comment by xTVaser** [comment]
This problem was likely caused by an invalid WebView2 installation -- a month or so ago there was a bad release, and it seems to be effecting some people.

https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section use the `x64` standalone installer -- you may have to run it as administrator for it to successfully install.
