### ISSUE TITLE
Launcher allows the user to pick an installation directory that cannot be written to

### ISSUE THREAD

**Issue by EtherDamon** [open-goal/launcher#125]
I updated the OpenGoal launcher to the latest release. When it says to download a tool version, clicking any version gives me a message saying "unable to download version". I cannot open the version folder either. Log below.

[2023-03-16.log](https://github.com/open-goal/launcher/files/10997354/2023-03-16.log)

**Comment by xTVaser** [comment]
That log file is empty, doesn't seem to be uploaded properly. https://github.com/open-goal/launcher#asking-for-help

**Comment by EtherDamon** [comment]
[2023-03-16.log](https://github.com/open-goal/launcher/files/10997374/2023-03-16.log)

Try this one.

**Comment by xTVaser** [comment]
Can you also upload your `settings.json` file -- the support package would include more than just the logs.

Looking at the logs, I see lines like:
```
Unable to prepare destination folder 'C:\Program Files\OpenGOAL-Launcher\versions\official\v0.1.33'
```

Implying you set your installation directory (not in the one in the MSI installer, the one in the launcher prompt) to `Program Files/OpenGOAL-Launcher`.

Writing to program files requires administrative privileges so that is likely the culprit.  I thought I prevented this but either way, this needs a better error if that is indeed the problem.

**I'd recommend trying to change the installation directory to a folder on your desktop or something and seeing if that works (you can change it from the settings page, and it might require a re-launch).**

![image](https://user-images.githubusercontent.com/13153231/225801547-fc96d288-3392-4bc8-886f-719cd871cfe5.png)

**Comment by EtherDamon** [comment]
The .json file is not attaching.

Ok. I changed the destination folder to a file in my downloads folder and now it is allowing me to download the tooling and compile the iso. Thank you!
