### ISSUE TITLE
whats the point of the discord???

### ISSUE THREAD

**Issue by PerculesIII** [open-goal/launcher#614]
Every time I have joined the discord I'm almost immediately removed. The same happens to many, many others. So whats the point of suggesting updates through discord if you're not going to let anyone in??????

**Comment by yodaxtah** [comment]
I believe it is required to provide your phone number somewhere to reduce spam/bots. The volunteers behind this project don't have the resources to manually check whether an account is a bot or not.

And we/they do let people in. Right now 1000s have joined. New people keep on joining on a weekly basis, probably.

**Comment by ManDude** [comment]
There are 5136 people in the server. Evidently it has worked for many people.

When you join the server you are immediately shown verification steps. If you are having trouble you should contact one of the admins there to take a look.

**Comment by xTVaser** [comment]
Assuming you are actually getting into the server (you have a verified phone number), You are auto-kicked in 5 minutes if you do not verify your account as not an alt when you join.  We were forced to add this protection to the server because we were having to deal with a few select people making several new spam accounts on the daily.

It may mean that some people are not able to join the server, either for personal privacy reasons (not wanting to go through the verification steps) or simply not being able to figure it out.  While unfortunate, I'm willing to take this risk, as spending hours dealing with moderation is not what we signed up for.
