### ISSUE TITLE
Properly support launching a REPL on linux

### ISSUE THREAD

**Issue by Hat-Kid** [open-goal/launcher#85]
Pressing the "Open REPL" button in the launcher starts the compiler in the background, unable to be used, and maxes out CPU usage.

![image](https://user-images.githubusercontent.com/6624576/209180325-dee82d94-b423-4589-b323-34c561fd9280.png)

**Comment by xTVaser** [comment]
Did some more investigating on this yesterday, as I figured / originally mentioned in the overhaul PR -- this is a challenge considering there is no default terminal on linux, _nor_ is there a default way to figure out what the user does.

on macOS there is a somewhat commonly used `TERM_PROGRAM` environment variable.  But this has been outright rejected by many linux/cross-platform terminal emulators, such as alacritty:
![image](https://github.com/open-goal/launcher/assets/13153231/f1ccd09b-b30a-4781-8af5-34e76858fd66)
It's also irrelevant, because macOS _has_ a default terminal emulator.

In typical linux fashion, there is no standard across distros and calling the notable solutions to this problem heuristics would be being quite generous.  So it seems like the only way to properly support this will be to make the user supply the binary / arg-info into the launcher so we know what the heck to execute.  Additional info on the linux side here - https://superuser.com/a/1461079

**Comment by fabjan** [comment]
I have no graphical Linux installs to test on, but reading a few of those discussions it looks like the environment variables `XDG_CURRENT_DESKTOP` or `XDG_MENU_PREFIX` could be used to see if someone is probably using a desktop environment with a known default terminal emulator.

Otherwise this can be ported: https://github.com/i3/i3/blob/next/i3-sensible-terminal, which launches the first one it finds of some known terminal emulators.

Or they can be combined to just use the same list but ordered differently per guessed desktop environment.

For Linux users that don't care, this should be a good enough solution. For Linux users who do care, they can edit settings and type their preferred terminal emulator command. (Or to save on complexity of the launcher code for this very specific case, actually use `$TERM_PROGRAM` or `$TERM` or `$TERMINAL` and tell the user to set it for their launcher use, they are obviously power users if they care that the "wrong" terminal emulator was launched.)

I think it's better to guess than to force all users to select one, even if they are linux users they might actually not know too much about the different alternatives. Of course provide some way to override the guess.

**Comment by xTVaser** [comment]
I feel like it's up to whoever takes up the challenge to implement it.  Personally I wouldn't want to go the `i3-sensible-terminal` route because it's a maintenance burden and you need to do more than just launch the terminal -- you have to launch it in a separate window / with the correct args, which may be different for each terminal emulator.

If I were to do the work, I would just make the user enter it in via settings because:
- using the REPL via the launcher is honestly not the ideal way anyway, a proper dev environment is infinitely better
- if the user can't figure out how to setup their settings accordingly, they likely won't be able to make effective use of the REPL either.

But yeah if someone is willing to do all the work to attempt to make it a more elegant solution _and maintain it_, there's no denying it would be better

**Comment by amarzot** [comment]
There is also https://github.com/Vladimir-csp/xdg-terminal-exec

recommended by the xdg people themselves: https://gitlab.freedesktop.org/xdg/xdg-utils/-/issues/241#note_2198276

and potentially will be included as a core utility eventually if I read that comment right
